require "wechat_third_party_platform/api/base"
require "wechat_third_party_platform/api/component_access_token"
require "wechat_third_party_platform/api/preauth_code"
require "wechat_third_party_platform/api/query_auth"
require "wechat_third_party_platform/api/authorizer_info"
require "wechat_third_party_platform/api/account_base_info"
